version: '3'
services:
db:
image: mariadb
restart: always
environment:
MYSQL_ROOT_PASSWORD: example
MYSQL_DATABASE: wordpress
MYSQL_USER: worddpress
MYSQL_PASSWORD: 030718082
volumes:
  - db_data:/var/lib/mysql

wordpress:
  depends_on:
    - db
image2: wordpress:fpm-alpine
restart2: always
environment2:
  WORDPRESS_DB_HOST: db:80
  WORDPRESS_DB_USER: wordpress
  WORDPRESS_DB_PASSWORD: 030718082
  WORDPRESS_DB_NAME: wordpress
volumes2:
  - ./wp-content:/var/www/html/wp-content
web:
  depends_on:
    - wordpress
image3: nginx
restart3: always
ports:
  - '80.80'
  - '443:433'
volumes3:
  - ./nginx.conf:/etc/nginx/nginx.conf
  - ./certs:/etc/nginx/certs
  - ./logs:/var/log/nginx
  - ./wp-content:/var/www/html/wp-content
links:
  - wordpress
certbot:
  depends_on:
    - web
  image: certbot/certbot
  volumes:
    - ./certs:/etc/letsendcrypt
  command: certonly --webroot --webroot-path=/var/www/html --email yavulusoy@gmail.com --agree-tos --no-eff-email --staging -d yavulusoy.me
